import Link from "next/link";
import { ArrowRight } from "@phosphor-icons/react/dist/ssr";
import { JsonLd } from "../../components/JsonLd";
import { SourcingCollections } from "../../components/SourcingCollections";
import { sourcingChecks, sourcingPrograms, sourcingReferences } from "../../sourcing-programs";
import { pageMetadata } from "../../lib/page-metadata";

export const metadata = pageMetadata("Foodservice Packaging for Distributors & Importers", "Build a wholesale shortlist of aluminium foil rolls, baking paper and food containers. Compare model specifications, matching lids, samples, documents and case packing for your destination.", "/distributors/");

const questions = [
  { question: "What should a distributor include in the first enquiry?", answer: "Send the product or closest format, destination country and state or region, buyer channel, intended food use and quantity by model. Include your current specification or component reference when available; an exact AW SKU is optional." },
  { question: "Can an existing product specification be used in another market?", answer: "It needs a separate review. Keep the existing reference and the proposed destination version distinct, including material, coatings, matching components, labels, documents and use conditions. A catalogue listing is not a destination approval." },
  { question: "Are lids included with aluminium containers?", answer: "Lid inclusion and compatibility are confirmed for the exact base and lid references. Request separate piece counts, case packing and pricing where the components are supplied separately." },
  { question: "How are MOQ, sample costs and lead time confirmed?", answer: "Request current terms for the selected model, material, artwork, packing, quantity unit and destination. Agree sample availability and costs, quotation validity and the approvals that start production timing before placing an order." },
];

export default function DistributorsPage() {
  const url = "https://anwellup.com/distributors/";
  return <main id="main-content" className="page-main distributor-page">
    <JsonLd data={[
      { "@context": "https://schema.org", "@type": "CollectionPage", "@id": `${url}#page`, url, name: "Foodservice packaging for distributors and importers", description: metadata.description, dateModified: "2026-10-08", isPartOf: { "@id": "https://anwellup.com/#website" }, mainEntity: { "@type": "ItemList", itemListElement: sourcingPrograms.map((program, index) => ({ "@type": "ListItem", position: index + 1, name: program.title, url: `https://anwellup.com${sourcingReferences(program)[0].href}` })) } },
      { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://anwellup.com/" }, { "@type": "ListItem", position: 2, name: "For distributors", item: url }] },
      { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: questions.map(item => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
    ]} />
    <nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">For distributors</span></nav>
    <header className="page-hero distributor-hero"><span className="eyebrow">For distributors & importers</span><h1>Build a clearer<br/>foodservice range.</h1><p>Put foil rolls, baking paper and food containers into one comparable buying brief. Start with the formats your customers use, then confirm the product version, components, documents and commercial terms for your destination.</p><div className="procurement-actions"><Link className="button button-dark" href="/contact/#send-enquiry">Discuss your shortlist <ArrowRight size={18} aria-hidden="true" /></Link><a className="button button-outline" href="#sourcing-range">Explore the buying routes</a></div></header>
    <section id="sourcing-range" className="sourcing-section" aria-labelledby="sourcing-range-title"><header><span className="eyebrow">A focused starting range</span><h2 id="sourcing-range-title">Start with the essentials.</h2><p>These are published catalogue references for comparison. Availability, dimensions, matching components and destination-specific versions are confirmed with the quotation.</p></header><SourcingCollections /></section>
    <section className="sourcing-section" aria-labelledby="channel-title"><header><span className="eyebrow">Your customers shape the specification</span><h2 id="channel-title">Source for the way they work.</h2></header><div className="sourcing-channels">
      <article><span>01 / Foodservice wholesalers</span><h3>A consistent replenishment brief.</h3><p>Define widths, roll lengths, portion sizes, case quantities and repeat-order requirements. Ask which specifications and packaging versions can remain consistent across batches.</p><Link href="/guides/food-packaging-materials-comparison/">Compare packaging materials →</Link></article>
      <article><span>02 / Bakery distributors</span><h3>Match the tray and process.</h3><p>Specify the baking tray, paper format, coating and actual temperature and time. Keep greaseproof wrapping and paper intended for baking as separate use requirements.</p><Link href="/products/foil-wraps-baking/foil-rolls-sheets-paper/#model-AW-BP-SHEET">Review the baking paper reference →</Link></article>
      <article><span>03 / Foodservice & coffee groups</span><h3>Build the complete pack.</h3><p>Review the food or beverage, portion and carrying routine with the base, lid and other components. Keep printing and packing approvals tied to the selected references.</p><Link href="/solutions/">Explore foodservice scenarios →</Link></article>
    </div></section>
    <section className="sourcing-section sourcing-review" aria-labelledby="sourcing-review-title"><header><span className="eyebrow">Before comparing quotations</span><h2 id="sourcing-review-title">Four parts of one order.</h2><p>Use the same specification, quantity unit and delivery basis across responses. An open field is a question to resolve with the proposed supplier.</p></header><div className="sourcing-checks">{sourcingChecks.map((check, index) => <article key={check.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{check.title}</h3><p>{check.body}</p></article>)}</div><div className="sourcing-resource-links"><Link href="/resources/food-packaging-rfq-template/">Download the RFQ workbook →</Link><Link href="/resources/carton-cbm-calculator/">Check carton CBM →</Link><Link href="/quality-compliance/">Review the document process →</Link></div></section>
    <section className="sourcing-section market-version-note" aria-labelledby="market-version-title"><div><span className="eyebrow">One reference, a defined destination</span><h2 id="market-version-title">Keep market versions clear.</h2></div><div><p>An established specification and a new destination version need their own records. State the country and state or region, sales channel and actual use so material, coating, component and document requirements can be reviewed together.</p><p>Keep the original trade names and sizes in the brief. Confirm measured dimensions, capacity definitions, tolerances and samples before making substitutions.</p><Link href="/guides/single-use-plastic-packaging-alternatives/">See the destination-review checklist →</Link></div></section>
    <section className="contact-questions"><h2>Questions before a wholesale enquiry.</h2><dl>{questions.map(item => <div key={item.question}><dt>{item.question}</dt><dd>{item.answer}</dd></div>)}</dl></section>
    <section className="family-next-step"><div><span className="eyebrow">Your next buying brief</span><h2>Start with the fields you know.</h2><p>Send your shortlist, destination and quantity. Request the model-specific sample options, document scope, packing, MOQ and current lead time.</p></div><Link className="button button-dark" href="/contact/#send-enquiry">Request a quotation <ArrowRight size={18} aria-hidden="true" /></Link></section>
  </main>;
}
