import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy", description: "How ANWELLUP handles enquiry details, locally stored product selections, security verification, email delivery, analytics and external contact links.", alternates: { canonical: "/privacy/" } };
export default function PrivacyPage() {
  return <main id="main-content" className="legal-page"><span className="eyebrow">Privacy / updated 30 September 2026</span><h1>How this website handles information.</h1><section>
    <h2>Product selections and draft details</h2><p>Selected product references are stored in your browser so you can return to your list. Contact details and project notes stay in the current page session until you choose a contact action. Clearing the list removes the selected products from browser storage.</p>
    <h2>Enquiries submitted on this website</h2><p>When you submit the enquiry form, your name, email, optional company and phone, destination, quantity, project notes and selected products are sent to our enquiry service. We use these details to assess and respond to your request. The page address is included without its search parameters.</p>
    <h2>Security and email delivery</h2><p>Cloudflare hosts the enquiry service and provides Turnstile security verification. The service checks the verification token and visitor IP with Cloudflare to reduce automated abuse. Resend processes the enquiry email for delivery to the ANWELLUP sales inbox. An accepted-enquiry reference confirms the service accepted the request; email delivery can still require follow-up.</p><p>Read the <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy policy</a> and <a href="https://resend.com/legal/privacy-policy">Resend privacy policy</a> for their processing practices.</p>
    <h2>Email and WhatsApp</h2><p>Choosing email or WhatsApp prepares your message in an external app. You review and send it there. These services have their own privacy practices. The copy-brief option writes your prepared message to your device clipboard only when you choose it.</p>
    <h2>Website measurement</h2><p>The website is configured to use Google Analytics and Microsoft Clarity for page use and non-sensitive actions such as product selection, catalogue downloads, contact clicks and accepted online enquiries. The enquiry form is marked for Clarity masking. Names, email addresses, phone numbers and project notes are not included in our analytics event parameters. Google Tag Manager can be used as an alternative analytics deployment mode. Hosting providers may also process security and access logs.</p>
    <h2>Questions about your data</h2><p>To ask about your enquiry information or request correction or deletion, contact <a href="mailto:admin@anwellup.com">admin@anwellup.com</a>. Enquiries are handled through the sales inbox and the service providers described above.</p>
  </section></main>;
}
