export type CategoryId = "plant" | "paper" | "aluminium" | "clear" | "hygiene";

export type Product = {
  sku: string;
  name: string;
  category: CategoryId;
  family: string;
  material: string;
  size: string;
  dimensions: string;
  casePack: string;
  image: string;
};

export type Category = {
  id: CategoryId;
  label: string;
  shortLabel: string;
  description: string;
  image: string;
};

const productImage = (name: string) => `/assets/products/${name}`;
const generatedProductImage = (sku: string) => `/assets/generated/products/${sku.toLowerCase()}.jpg`;

export const categories: Category[] = [
  {
    id: "plant",
    label: "Plant Fiber",
    shortLabel: "Plant Fiber",
    description: "Bagasse clamshells, bowls, plates and meal trays for hot and cold food programs.",
    image: "/assets/generated/scenes/category-plant-fiber.jpg",
  },
  {
    id: "paper",
    label: "Paper + Kraft",
    shortLabel: "Paper + Kraft",
    description: "Printable cups, bowls and takeaway formats with broad foodservice acceptance.",
    image: "/assets/generated/scenes/category-paper-kraft.jpg",
  },
  {
    id: "aluminium",
    label: "Aluminium",
    shortLabel: "Aluminium",
    description: "Barrier and heat performance across containers, rolls, sheets and baking paper.",
    image: "/assets/generated/scenes/category-aluminium.jpg",
  },
  {
    id: "clear",
    label: "Clear + Performance",
    shortLabel: "PET + PP",
    description: "High-clarity drinkware and prepared-food formats where visibility matters.",
    image: "/assets/generated/scenes/category-clear-performance.jpg",
  },
  {
    id: "hygiene",
    label: "Hygiene Essentials",
    shortLabel: "Gloves",
    description: "Selected vinyl, nitrile and TPE handling gloves for operational use.",
    image: "/assets/generated/scenes/category-hygiene.jpg",
  },
];

export const products: Product[] = ([
  {
    sku: "AW-BG-H96",
    name: "9 x 6 in Hinged Container",
    category: "plant",
    family: "Hinged Containers",
    material: "Sugarcane bagasse",
    size: "9 x 6 in",
    dimensions: "250 x 165 x 65 mm",
    casePack: "500 pcs",
    image: productImage("bag_clamshell_1.png"),
  },
  {
    sku: "AW-BG-H66",
    name: "6 x 6 in Hinged Container",
    category: "plant",
    family: "Hinged Containers",
    material: "Sugarcane bagasse",
    size: "6 x 6 in",
    dimensions: "155 x 150 x 80 mm",
    casePack: "500 pcs",
    image: productImage("bag_clamshell_2.png"),
  },
  {
    sku: "AW-BG-H99",
    name: "9 x 9 in Hinged Container",
    category: "plant",
    family: "Hinged Containers",
    material: "Sugarcane bagasse",
    size: "9 x 9 in",
    dimensions: "205 x 205 x 80 mm",
    casePack: "250 pcs",
    image: productImage("bag_clamshell_3.png"),
  },
  {
    sku: "AW-BG-H88",
    name: "8 x 8 in Hinged Container",
    category: "plant",
    family: "Hinged Containers",
    material: "Sugarcane bagasse",
    size: "8 x 8 in",
    dimensions: "205 x 220 x 70 mm",
    casePack: "500 pcs",
    image: productImage("bag_clamshell_4.png"),
  },
  {
    sku: "AW-BG-B12",
    name: "Molded Fiber Bowl",
    category: "plant",
    family: "Bowls",
    material: "Sugarcane bagasse",
    size: "340 ml / 12 oz",
    dimensions: "Dia. 152 x 45.6 mm",
    casePack: "500 pcs",
    image: productImage("bag_bowl_1.png"),
  },
  {
    sku: "AW-BG-B24",
    name: "Molded Fiber Bowl",
    category: "plant",
    family: "Bowls",
    material: "Sugarcane bagasse",
    size: "680 ml / 24 oz",
    dimensions: "Dia. 189 x 40.6 mm",
    casePack: "1,000 pcs",
    image: productImage("bag_bowl_2.png"),
  },
  {
    sku: "AW-BG-B32",
    name: "Molded Fiber Bowl",
    category: "plant",
    family: "Bowls",
    material: "Sugarcane bagasse",
    size: "950 ml / 32 oz",
    dimensions: "Dia. 175 x 67 mm",
    casePack: "600 pcs",
    image: productImage("bag_bowl_3.png"),
  },
  {
    sku: "AW-BG-B14",
    name: "Molded Fiber Bowl",
    category: "plant",
    family: "Bowls",
    material: "Sugarcane bagasse",
    size: "400 ml / 14 oz",
    dimensions: "Dia. 178 x 40.6 mm",
    casePack: "1,000 pcs",
    image: productImage("bag_bowl_4.png"),
  },
  {
    sku: "AW-BG-P08",
    name: "8 in Ribbed Plate",
    category: "plant",
    family: "Plates",
    material: "Sugarcane bagasse",
    size: "8 in",
    dimensions: "Dia. 210 x 18.6 mm",
    casePack: "1,000 pcs",
    image: productImage("bag_plate_1.png"),
  },
  {
    sku: "AW-BG-P10",
    name: "10 in Dinner Plate",
    category: "plant",
    family: "Plates",
    material: "Sugarcane bagasse",
    size: "10 in",
    dimensions: "Dia. 261 x 20.6 mm",
    casePack: "500 pcs",
    image: productImage("bag_plate_2.png"),
  },
  {
    sku: "AW-BG-P10C",
    name: "10 in 3-Compartment Plate",
    category: "plant",
    family: "Plates",
    material: "Sugarcane bagasse",
    size: "10 in / 3 sections",
    dimensions: "Dia. 261 x 25.6 mm",
    casePack: "500 pcs",
    image: productImage("bag_plate_3.png"),
  },
  {
    sku: "AW-BG-P675",
    name: "6.75 in Plate",
    category: "plant",
    family: "Plates",
    material: "Sugarcane bagasse",
    size: "6.75 in",
    dimensions: "Dia. 174 x 15 mm",
    casePack: "500 pcs",
    image: productImage("bag_plate_4.png"),
  },
  {
    sku: "AW-BG-T30",
    name: "Rectangular Meal Tray",
    category: "plant",
    family: "Meal Trays",
    material: "Sugarcane bagasse",
    size: "900 ml / 30 oz",
    dimensions: "200 x 155 x 45 mm",
    casePack: "600 pcs",
    image: productImage("bag_tray_1.png"),
  },
  {
    sku: "AW-BG-T23",
    name: "Rectangular Meal Tray",
    category: "plant",
    family: "Meal Trays",
    material: "Sugarcane bagasse",
    size: "650 ml / 23 oz",
    dimensions: "170 x 120 x 40 mm",
    casePack: "600 pcs",
    image: productImage("bag_tray_2.png"),
  },
  {
    sku: "AW-BG-T3C-L",
    name: "3-Compartment Meal Tray",
    category: "plant",
    family: "Meal Trays",
    material: "Sugarcane bagasse",
    size: "3 sections",
    dimensions: "270 x 170 x 52 mm",
    casePack: "400 pcs",
    image: productImage("bag_tray_3.png"),
  },
  {
    sku: "AW-BG-T3C-M",
    name: "3-Compartment Meal Tray",
    category: "plant",
    family: "Meal Trays",
    material: "Sugarcane bagasse",
    size: "3 sections",
    dimensions: "225 x 175 x 40 mm",
    casePack: "400 pcs",
    image: productImage("bag_tray_4.png"),
  },
  {
    sku: "AW-PC-S08",
    name: "Single-Wall Paper Cup",
    category: "paper",
    family: "Paper Cups",
    material: "Food-grade paper",
    size: "8 oz",
    dimensions: "90 x H85 x 56 mm",
    casePack: "1,000 pcs",
    image: productImage("paper_cup_1.png"),
  },
  {
    sku: "AW-PC-D12",
    name: "Double-Wall Paper Cup",
    category: "paper",
    family: "Paper Cups",
    material: "Food-grade paper",
    size: "12 oz",
    dimensions: "90 x H111 x 60 mm",
    casePack: "500 pcs",
    image: productImage("paper_cup_2.png"),
  },
  {
    sku: "AW-PC-D16",
    name: "Double-Wall Paper Cup",
    category: "paper",
    family: "Paper Cups",
    material: "Food-grade paper",
    size: "16 oz",
    dimensions: "90 x H135 x 60 mm",
    casePack: "500 pcs",
    image: productImage("paper_cup_3.png"),
  },
  {
    sku: "AW-PC-S20",
    name: "Single-Wall Paper Cup",
    category: "paper",
    family: "Paper Cups",
    material: "Food-grade paper",
    size: "20 oz",
    dimensions: "90 x H160 x 60 mm",
    casePack: "1,000 pcs",
    image: productImage("paper_cup_4.png"),
  },
  {
    sku: "AW-PB-500",
    name: "Kraft Paper Bowl",
    category: "paper",
    family: "Kraft Paper Bowls",
    material: "Kraft paper",
    size: "500 ml",
    dimensions: "150 x H45 x 130 mm",
    casePack: "300 pcs",
    image: productImage("paper_bowl_1.png"),
  },
  {
    sku: "AW-PB-750",
    name: "Kraft Paper Bowl",
    category: "paper",
    family: "Kraft Paper Bowls",
    material: "Kraft paper",
    size: "750 ml",
    dimensions: "150 x H60 x 130 mm",
    casePack: "300 pcs",
    image: productImage("paper_bowl_2.png"),
  },
  {
    sku: "AW-PB-1300",
    name: "Kraft Paper Bowl",
    category: "paper",
    family: "Kraft Paper Bowls",
    material: "Kraft paper",
    size: "1,300 ml",
    dimensions: "185 x H64.5 x 160 mm",
    casePack: "300 pcs",
    image: productImage("paper_bowl_3.png"),
  },
  {
    sku: "AW-PB-2000",
    name: "Kraft Paper Bowl",
    category: "paper",
    family: "Kraft Paper Bowls",
    material: "Kraft paper",
    size: "2,000 ml",
    dimensions: "204 x H65 x 180 mm",
    casePack: "300 pcs",
    image: productImage("paper_bowl_4.png"),
  },
  {
    sku: "AW-PK-500",
    name: "Square Takeaway Container",
    category: "paper",
    family: "Takeaway Containers",
    material: "Kraft paper",
    size: "500 ml",
    dimensions: "130.8 x H49 x 112 mm",
    casePack: "500 pcs",
    image: productImage("kraft_takeaway_1.png"),
  },
  {
    sku: "AW-PK-750",
    name: "Square Takeaway Container",
    category: "paper",
    family: "Takeaway Containers",
    material: "Kraft paper",
    size: "750 ml",
    dimensions: "171.2 x H45 x 149 mm",
    casePack: "500 pcs",
    image: productImage("kraft_takeaway_2.png"),
  },
  {
    sku: "AW-PK-1000",
    name: "Square Takeaway Container",
    category: "paper",
    family: "Takeaway Containers",
    material: "Kraft paper",
    size: "1,000 ml",
    dimensions: "171.2 x H56 x 150 mm",
    casePack: "500 pcs",
    image: productImage("kraft_takeaway_3.png"),
  },
  {
    sku: "AW-PK-1500",
    name: "Large Takeaway Box",
    category: "paper",
    family: "Takeaway Containers",
    material: "Kraft paper",
    size: "1,500 ml",
    dimensions: "215 x H48 x 160 mm",
    casePack: "200 pcs",
    image: productImage("kraft_takeaway_4.png"),
  },
  {
    sku: "AW-PK-BOAT-1",
    name: "Kraft Boat Tray",
    category: "paper",
    family: "Foodservice Formats",
    material: "Kraft paper",
    size: "No. 1",
    dimensions: "75 x H28 x 48 mm",
    casePack: "1,000 pcs",
    image: productImage("boat_tray_1.png"),
  },
  {
    sku: "AW-PK-BOAT-2",
    name: "Kraft Boat Tray",
    category: "paper",
    family: "Foodservice Formats",
    material: "Kraft paper",
    size: "No. 2",
    dimensions: "86 x H35 x 51 mm",
    casePack: "1,000 pcs",
    image: productImage("boat_tray_2.png"),
  },
  {
    sku: "AW-PK-BOAT-4",
    name: "Kraft Boat Tray",
    category: "paper",
    family: "Foodservice Formats",
    material: "Kraft paper",
    size: "No. 4",
    dimensions: "105 x H43 x 75 mm",
    casePack: "500 pcs",
    image: productImage("boat_tray_3.png"),
  },
  {
    sku: "AW-PK-N16",
    name: "Noodle Box",
    category: "paper",
    family: "Foodservice Formats",
    material: "Food-grade paper",
    size: "16 oz",
    dimensions: "135.5 x H152 x 94 mm",
    casePack: "500 pcs",
    image: productImage("noodle_box_16.png"),
  },
  {
    sku: "AW-AL-S300",
    name: "Smoothwall Foil Container",
    category: "aluminium",
    family: "Smoothwall Containers",
    material: "Aluminium",
    size: "300 ml",
    dimensions: "160 x 105 x 28 mm",
    casePack: "1,000 pcs",
    image: productImage("alu_smooth_1.png"),
  },
  {
    sku: "AW-AL-S350",
    name: "Smoothwall Foil Container",
    category: "aluminium",
    family: "Smoothwall Containers",
    material: "Aluminium",
    size: "350 ml",
    dimensions: "159 x 103 x 30 mm",
    casePack: "1,000 pcs",
    image: productImage("alu_smooth_2.png"),
  },
  {
    sku: "AW-AL-S380",
    name: "Smoothwall Foil Container",
    category: "aluminium",
    family: "Smoothwall Containers",
    material: "Aluminium",
    size: "380 ml",
    dimensions: "168 x 103 x 33 mm",
    casePack: "1,000 pcs",
    image: productImage("alu_smooth_3.png"),
  },
  {
    sku: "AW-AL-S450",
    name: "Smoothwall Foil Container",
    category: "aluminium",
    family: "Smoothwall Containers",
    material: "Aluminium",
    size: "450 ml",
    dimensions: "173 x 93 x 40 mm",
    casePack: "1,000 pcs",
    image: productImage("alu_smooth_4.png"),
  },
  {
    sku: "AW-AL-G400",
    name: "Premium Square Foil Bowl",
    category: "aluminium",
    family: "Premium Color Series",
    material: "Coated aluminium",
    size: "400 ml",
    dimensions: "139 x 139 x 45 mm",
    casePack: "1,000 pcs",
    image: productImage("alu_gold_1.png"),
  },
  {
    sku: "AW-AL-G1450",
    name: "Premium Square Foil Tray",
    category: "aluminium",
    family: "Premium Color Series",
    material: "Coated aluminium",
    size: "1,450 ml",
    dimensions: "210 x 210 x 61 mm",
    casePack: "500 pcs",
    image: productImage("alu_gold_2.png"),
  },
  {
    sku: "AW-AL-G1000S",
    name: "Premium Square Foil Tray",
    category: "aluminium",
    family: "Premium Color Series",
    material: "Coated aluminium",
    size: "1,000 ml",
    dimensions: "185 x 185 x 61 mm",
    casePack: "500 pcs",
    image: productImage("alu_gold_3.png"),
  },
  {
    sku: "AW-AL-G1000R",
    name: "Premium Round Foil Bowl",
    category: "aluminium",
    family: "Premium Color Series",
    material: "Coated aluminium",
    size: "1,000 ml",
    dimensions: "Dia. 186 x 52 mm",
    casePack: "500 pcs",
    image: productImage("alu_gold_4.png"),
  },
  {
    sku: "AW-AL-W500",
    name: "Wrinkle-Wall Foil Tray",
    category: "aluminium",
    family: "Wrinkle-Wall Containers",
    material: "Aluminium",
    size: "500 ml",
    dimensions: "148 x 121 x 46 mm",
    casePack: "500 pcs",
    image: productImage("alu_wrinkle_1.png"),
  },
  {
    sku: "AW-AL-W1150",
    name: "Wrinkle-Wall Foil Tray",
    category: "aluminium",
    family: "Wrinkle-Wall Containers",
    material: "Aluminium",
    size: "1,150 ml",
    dimensions: "228 x 170 x 38 mm",
    casePack: "500 pcs",
    image: productImage("alu_wrinkle_2.png"),
  },
  {
    sku: "AW-AL-W3600",
    name: "Large Roasting Foil Tray",
    category: "aluminium",
    family: "Wrinkle-Wall Containers",
    material: "Aluminium",
    size: "3,600 ml",
    dimensions: "455 x 365 x 86 mm",
    casePack: "50 pcs",
    image: productImage("alu_wrinkle_3.png"),
  },
  {
    sku: "AW-AL-W830C",
    name: "2-Compartment Foil Tray",
    category: "aluminium",
    family: "Wrinkle-Wall Containers",
    material: "Aluminium",
    size: "830 ml",
    dimensions: "226 x 177 x 32 mm",
    casePack: "1,000 pcs",
    image: productImage("alu_wrinkle_4.png"),
  },
  {
    sku: "AW-AF-C300",
    name: "Catering Foil Roll",
    category: "aluminium",
    family: "Rolls, Sheets + Paper",
    material: "Aluminium",
    size: "300 / 450 mm widths",
    dimensions: "60-300 m roll options",
    casePack: "Custom program",
    image: productImage("foil_roll_catering.png"),
  },
  {
    sku: "AW-AF-H300",
    name: "Household Foil Roll",
    category: "aluminium",
    family: "Rolls, Sheets + Paper",
    material: "Aluminium",
    size: "250 / 300 / 450 mm",
    dimensions: "10-50 m retail options",
    casePack: "Custom program",
    image: productImage("foil_roll_household.png"),
  },
  {
    sku: "AW-BP-SHEET",
    name: "Silicone Baking Paper",
    category: "aluminium",
    family: "Rolls, Sheets + Paper",
    material: "Baking paper",
    size: "Sheet + roll formats",
    dimensions: "39-41 gsm options",
    casePack: "Custom program",
    image: productImage("baking_paper.png"),
  },
  {
    sku: "AW-AF-POP",
    name: "Pop-Up Foil Sheets",
    category: "aluminium",
    family: "Rolls, Sheets + Paper",
    material: "Aluminium",
    size: "Pre-cut dispensing",
    dimensions: "Multiple sheet sizes",
    casePack: "Custom program",
    image: productImage("foil_sheets.png"),
  },
  {
    sku: "AW-PET-C07",
    name: "Clear Cold Cup",
    category: "clear",
    family: "PET Cold Cups",
    material: "PET",
    size: "7 oz",
    dimensions: "78.5 x H80.6 x 49.5 mm",
    casePack: "1,000 pcs",
    image: productImage("pet_cup_1.png"),
  },
  {
    sku: "AW-PET-C08",
    name: "Clear Cold Cup",
    category: "clear",
    family: "PET Cold Cups",
    material: "PET",
    size: "8 oz",
    dimensions: "78.5 x H80.6 x 44.8 mm",
    casePack: "1,000 pcs",
    image: productImage("pet_cup_2.png"),
  },
  {
    sku: "AW-PET-C09",
    name: "Clear Cold Cup",
    category: "clear",
    family: "PET Cold Cups",
    material: "PET",
    size: "9 oz",
    dimensions: "78.5 x H96.6 x 45 mm",
    casePack: "1,000 pcs",
    image: productImage("pet_cup_3.png"),
  },
  {
    sku: "AW-PET-C10",
    name: "Clear Cold Cup",
    category: "clear",
    family: "PET Cold Cups",
    material: "PET",
    size: "10 oz",
    dimensions: "78.5 x H101.5 x 48.3 mm",
    casePack: "1,000 pcs",
    image: productImage("pet_cup_4.png"),
  },
  {
    sku: "AW-PET-TE08",
    name: "Tamper-Evident Container",
    category: "clear",
    family: "Tamper-Evident Containers",
    material: "PET",
    size: "8 oz",
    dimensions: "140 x H38 x 130 mm",
    casePack: "200 pcs",
    image: productImage("pet_tamper_1.png"),
  },
  {
    sku: "AW-PET-TE16",
    name: "Tamper-Evident Container",
    category: "clear",
    family: "Tamper-Evident Containers",
    material: "PET",
    size: "16 oz",
    dimensions: "140 x H65 x 130 mm",
    casePack: "200 pcs",
    image: productImage("pet_tamper_2.png"),
  },
  {
    sku: "AW-PET-TE24",
    name: "Tamper-Evident Container",
    category: "clear",
    family: "Tamper-Evident Containers",
    material: "PET",
    size: "24 oz",
    dimensions: "180 x H55 x 145 mm",
    casePack: "200 pcs",
    image: productImage("pet_tamper_3.png"),
  },
  {
    sku: "AW-PET-TE32",
    name: "Tamper-Evident Container",
    category: "clear",
    family: "Tamper-Evident Containers",
    material: "PET",
    size: "32 oz",
    dimensions: "188 x H70 x 145 mm",
    casePack: "200 pcs",
    image: productImage("pet_tamper_4.png"),
  },
  {
    sku: "AW-SU-805",
    name: "Sushi Box with Clear Lid",
    category: "clear",
    family: "Sushi + Hinged Containers",
    material: "PP tray / OPS lid",
    size: "No. 805",
    dimensions: "Tray 138 x H38 x 110 mm",
    casePack: "600 pcs",
    image: productImage("sushi_box_1.png"),
  },
  {
    sku: "AW-SU-825",
    name: "Sushi Box with Clear Lid",
    category: "clear",
    family: "Sushi + Hinged Containers",
    material: "PP tray / OPS lid",
    size: "No. 825",
    dimensions: "Tray 233 x H44 x 163 mm",
    casePack: "400 pcs",
    image: productImage("sushi_box_2.png"),
  },
  {
    sku: "AW-PET-H16",
    name: "Clear Hinged Container",
    category: "clear",
    family: "Sushi + Hinged Containers",
    material: "PET",
    size: "16 oz",
    dimensions: "148 x H61 x 126 mm",
    casePack: "200 pcs",
    image: productImage("salad_1.png"),
  },
  {
    sku: "AW-PET-H32",
    name: "Clear Hinged Container",
    category: "clear",
    family: "Sushi + Hinged Containers",
    material: "PET",
    size: "32 oz",
    dimensions: "189 x H68 x 161 mm",
    casePack: "200 pcs",
    image: productImage("salad_2.png"),
  },
  {
    sku: "AW-GL-VINYL",
    name: "Disposable Vinyl Gloves",
    category: "hygiene",
    family: "Handling Gloves",
    material: "Vinyl",
    size: "Clear / blue / black",
    dimensions: "Color options",
    casePack: "100 pcs/box; 10 boxes/carton",
    image: productImage("glove_vinyl_clean.png"),
  },
  {
    sku: "AW-GL-NITRILE",
    name: "Disposable Nitrile Gloves",
    category: "hygiene",
    family: "Handling Gloves",
    material: "Nitrile",
    size: "Blue / black / white / pink",
    dimensions: "Color options",
    casePack: "100 pcs/box; 10 boxes/carton",
    image: productImage("glove_nitrile_clean.png"),
  },
  {
    sku: "AW-GL-TPE",
    name: "Disposable TPE Gloves",
    category: "hygiene",
    family: "Handling Gloves",
    material: "TPE",
    size: "Clear / blue / black",
    dimensions: "Color options",
    casePack: "100 pcs/box; 10 boxes/carton",
    image: productImage("glove_tpe_clean.png"),
  },
] as Product[]).map((product) => ({
  ...product,
  image: generatedProductImage(product.sku),
}));
